#ifndef CORE_CONFIG_HPP
#define CORE_CONFIG_HPP

#define DEFAULT_SCREEN_WIDTH  1440
#define DEFAULT_SCREEN_HEIGHT 960

#define GAME_GL_MAJOR_VERSION 4
#define GAME_GL_MINOR_VERSION 1

#define GAME_GL_SAMPLE_RATE   4

#endif