#ifndef CORE_CONFIG_HPP
#define CORE_CONFIG_HPP

#define DEFAULT_SCREEN_WIDTH  800
#define DEFAULT_SCREEN_HEIGHT 600

#define GAME_GL_MAJOR_VERSION 4
#define GAME_GL_MINOR_VERSION 4

#define GAME_GL_SAMPLE_RATE   8

#endif