#ifndef GAMESCENE_CONFIG
#define GAMESCENE_CONFIG

#define TURNAROUND_DURATION 40.0
#define NIGHT_DURATION  20.0
#define DAY_DURATION    20.0

#define TERRAIN_HEIGHT_MAX 30.0
#define TERRAIN_OCTAVE 11.0
#define TERRAIN_TESS 1.0
#define CHUNK_WIDTH 50.0
#define CHUNK_HEIGHT 50.0
#define CHUNK_PLACE_X -25.0
#define CHUNK_PLACE_Z -25.0

#endif